### ISSUE TITLE
Add support PhpStorm 2024.3 EAP

### ISSUE THREAD

**Issue by CrazyBoy49z** [aSemy/ij-problem-ignorer#1]
Add support PhpStorm 2024.3 EAP

**Comment by aSemy** [comment]
Hi, please can you try version 0.0.6?

https://plugins.jetbrains.com/plugin/25023-problem-ignorer/versions/stable/606313

This is my first IntelliJ plugin and I find the version compatibility very confusing, so if you could try version 0.0.6 tell me what you find I'd really appreciate it.

**Comment by CrazyBoy49z** [comment]
<img width="460" alt="image" src="https://github.com/user-attachments/assets/6f5358a7-6cc6-424c-abdd-7a6d8fd6e471">

**Comment by aSemy** [comment]
Thanks for the update. I'm not sure how to add support though. Are you able to make a pull request?

**Comment by CrazyBoy49z** [comment]
> Thanks for the update. I'm not sure how to add support though. Are you able to make a pull request?

I will try to figure it out later, unfortunately I did not have such a case

**Comment by aSemy** [comment]
Hi, I've figured out the fix!

See https://github.com/aSemy/ij-problem-ignorer/commit/4c944a892857ef09d2f0bbae845192b5e6dc812e

<img width="912" alt="image" src="https://github.com/user-attachments/assets/7fe58475-52a4-4ec6-b86f-0371318a512b">

Thanks for the report!
